"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const auth_1 = require("../../middleware/auth");
const auditLog_1 = require("../../middleware/auditLog");
const customerController_1 = require("../../controllers/admin/customerController");
const router = (0, express_1.Router)();
router.use(auth_1.requireAuth, (0, auth_1.requireRole)("admin"), auditLog_1.auditLog);
router.get("/", customerController_1.listCustomers);
exports.default = router;
